/*
 * This source file was generated by the Gradle 'init' task
 */
package stock.tracker;

import java.awt.AWTException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.JTextComponent;

public class App extends JFrame {
    private final DefaultTableModel tableModel;
    private final DefaultComboBoxModel<String> groupComboModel;
    private final DefaultListModel<String> groupListModel;
    private final JTextArea logArea;
    private final JTextArea newsArea;
    private final JLabel marketStatusLabel;
    private final Map<String, String> symbolGroupMap;
    private final WatchlistStore watchlistStore;
    private final StockQuoteService quoteService;
    private final StockNewsService newsService;
    private final ScheduledExecutorService scheduler;
    private TrayIcon trayIcon;
    private boolean systemTraySupported = false;
    private String currentDirection = "";
    private String lastRefreshTime = "";
    private int lastRefreshedRows = 0;
    private JList<String> groupList;
    private String pendingSelectedGroup = "";
        private static final List<String> DEFAULT_TICKER_SUGGESTIONS = List.of(
            "AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "NVDA", "META", "V", "JNJ", "NFLX"
        );

    public App() {
        super("Stock Tracker");
        symbolGroupMap = new LinkedHashMap<>();
        watchlistStore = new WatchlistStore();
        quoteService = new StockQuoteService();
        newsService = new StockNewsService();
        scheduler = Executors.newSingleThreadScheduledExecutor();

        tableModel = new DefaultTableModel(new String[]{"Symbol", "Price", "Change", "% Change", "Name", "Updated"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        groupComboModel = new DefaultComboBoxModel<>();
        groupListModel = new DefaultListModel<>();
        logArea = new JTextArea(6, 1);
        newsArea = new JTextArea(6, 1);
        marketStatusLabel = new JLabel("Loading market feed...");

        loadWatchlist();
        initUI();
        initSystemTray();
        startRefreshTimer();
        refreshQuotesAsync();
    }

    private void initUI() {
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        setSize(1000, 680);
        setLocationRelativeTo(null);

        Container content = getContentPane();
        content.setBackground(new Color(16, 22, 35));
        content.setLayout(new BorderLayout(14, 14));

        JPanel headerPanel = new JPanel(new BorderLayout(8, 8));
        headerPanel.setOpaque(false);
        headerPanel.setBorder(new EmptyBorder(12, 16, 0, 16));

        JLabel titleLabel = new JLabel("Stocks");
        titleLabel.setFont(new Font("SansSerif", Font.BOLD, 34));
        titleLabel.setForeground(new Color(255, 255, 255));

        JLabel subtitleLabel = new JLabel("Live tickers, groups, and market direction.");
        subtitleLabel.setFont(new Font("SansSerif", Font.PLAIN, 14));
        subtitleLabel.setForeground(new Color(180, 185, 200));

        JPanel titleBlock = new JPanel(new BorderLayout(6, 6));
        titleBlock.setOpaque(false);
        titleBlock.add(titleLabel, BorderLayout.NORTH);
        titleBlock.add(subtitleLabel, BorderLayout.SOUTH);

        headerPanel.add(titleBlock, BorderLayout.WEST);

        marketStatusLabel.setFont(new Font("SansSerif", Font.BOLD, 14));
        marketStatusLabel.setOpaque(false);
        marketStatusLabel.setForeground(new Color(76, 175, 80));
        marketStatusLabel.setBorder(BorderFactory.createEmptyBorder(10, 16, 10, 16));
        marketStatusLabel.setHorizontalAlignment(JLabel.RIGHT);
        headerPanel.add(marketStatusLabel, BorderLayout.EAST);

        content.add(headerPanel, BorderLayout.NORTH);

        JPanel mainPanel = new JPanel(new BorderLayout(14, 14));
        mainPanel.setOpaque(false);
        mainPanel.setBorder(new EmptyBorder(0, 16, 16, 16));

        JPanel actionCard = new RoundedPanel(26, new Color(25, 32, 50));
        actionCard.setLayout(new GridBagLayout());
        actionCard.setBorder(new EmptyBorder(18, 18, 18, 18));
        actionCard.setPreferredSize(new Dimension(0, 130));

        GridBagConstraints c = new GridBagConstraints();
        c.insets = new Insets(8, 8, 8, 8);
        c.anchor = GridBagConstraints.WEST;
        c.fill = GridBagConstraints.HORIZONTAL;

        JLabel tickerLabel = new JLabel("Ticker");
        tickerLabel.setFont(new Font("SansSerif", Font.PLAIN, 13));
        tickerLabel.setForeground(new Color(150, 160, 175));
        c.gridx = 0;
        c.gridy = 0;
        actionCard.add(tickerLabel, c);

        DefaultComboBoxModel<String> symbolSuggestionModel = new DefaultComboBoxModel<>();
        JComboBox<String> symbolField = new JComboBox<>(symbolSuggestionModel);
        symbolField.setEditable(true);
        symbolField.setFont(new Font("SansSerif", Font.BOLD, 16));
        symbolField.setPreferredSize(new Dimension(110, 40));
        symbolField.setMinimumSize(new Dimension(110, 40));
        symbolField.setPrototypeDisplayValue("WWWWW");
        symbolField.setMaximumRowCount(5);
        symbolField.setBackground(new Color(16, 22, 35));
        symbolField.setForeground(new Color(255, 255, 255));
        c.gridx = 1;
        c.gridy = 0;
        c.weightx = 0.0;
        actionCard.add(symbolField, c);

        symbolField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                symbolField.hidePopup();
            }
        });

        JTextComponent symbolEditor = (JTextComponent) symbolField.getEditor().getEditorComponent();
        symbolEditor.setBackground(new Color(16, 22, 35));
        symbolEditor.setForeground(new Color(255, 255, 255));
        symbolEditor.setCaretColor(new Color(255, 255, 255));
        setupPlaceholder(symbolEditor, "Search Ticker..");
        if (symbolEditor.getDocument() instanceof AbstractDocument doc) {
            doc.setDocumentFilter(new DocumentFilter() {
                @Override
                public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                    replace(fb, offset, 0, string, attr);
                }

                @Override
                public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                    if (text == null) {
                        return;
                    }
                    String filtered = text.toUpperCase(Locale.US).replaceAll("[^A-Z0-9.]", "");
                    int currentLength = fb.getDocument().getLength();
                    int available = Math.max(0, 5 - (currentLength - length));
                    if (filtered.length() > available) {
                        filtered = filtered.substring(0, available);
                    }
                    if (filtered.isEmpty()) {
                        return;
                    }
                    super.replace(fb, offset, length, filtered, attrs);
                }
            });
        }

        Timer suggestionTimer = new Timer(300, e -> {
            String query = getTickerInput(symbolField).trim();
            if (query.isBlank()) {
                symbolSuggestionModel.removeAllElements();
                symbolField.hidePopup();
                return;
            }
            fetchTickerSuggestions(query, symbolSuggestionModel, symbolField);
        });
        suggestionTimer.setRepeats(false);

        symbolEditor.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                suggestionTimer.restart();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                suggestionTimer.restart();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                suggestionTimer.restart();
            }
        });

        JLabel groupLabel = new JLabel("Group");
        groupLabel.setFont(new Font("SansSerif", Font.PLAIN, 13));
        groupLabel.setForeground(new Color(150, 160, 175));
        c.gridx = 2;
        c.gridy = 0;
        c.weightx = 0.0;
        actionCard.add(groupLabel, c);

        JComboBox<String> groupCombo = new JComboBox<>(groupComboModel);
        groupCombo.setEditable(true);
        groupCombo.setFont(new Font("SansSerif", Font.PLAIN, 14));
        groupCombo.setPreferredSize(new Dimension(140, 40));
        groupCombo.setBackground(new Color(16, 22, 35));
        groupCombo.setForeground(new Color(255, 255, 255));
        ((JLabel)groupCombo.getRenderer()).setOpaque(true);
        
        // Setup placeholder for group combobox
        JTextComponent groupEditor = (JTextComponent) groupCombo.getEditor().getEditorComponent();
        groupEditor.setBackground(new Color(16, 22, 35));
        groupEditor.setForeground(new Color(255, 255, 255));
        groupEditor.setCaretColor(new Color(255, 255, 255));
        setupPlaceholder(groupEditor, "Select Group");
        
        c.gridx = 3;
        c.gridy = 0;
        actionCard.add(groupCombo, c);

        JButton addSymbolButton = createPrimaryButton("+ Add Ticker");
        addSymbolButton.setPreferredSize(new Dimension(120, 40));
        c.gridx = 4;
        c.gridy = 0;
        c.weightx = 0.0;
        actionCard.add(addSymbolButton, c);

        mainPanel.add(actionCard, BorderLayout.NORTH);

        JTable quoteTable = new JTable(tableModel);
        quoteTable.setShowGrid(false);
        quoteTable.setIntercellSpacing(new Dimension(0, 0));
        quoteTable.setRowHeight(40);
        quoteTable.setFont(new Font("SansSerif", Font.PLAIN, 14));
        quoteTable.setForeground(new Color(220, 225, 235));
        quoteTable.setBackground(new Color(25, 32, 50));
        quoteTable.setFillsViewportHeight(true);
        quoteTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        quoteTable.setRowSelectionAllowed(true);
        quoteTable.setSelectionBackground(new Color(41, 121, 255));
        quoteTable.setSelectionForeground(Color.WHITE);

        JTableHeader header = quoteTable.getTableHeader();
        header.setBackground(new Color(35, 45, 65));
        header.setForeground(new Color(150, 160, 175));
        header.setFont(new Font("SansSerif", Font.BOLD, 12));
        header.setReorderingAllowed(false);
        header.setResizingAllowed(true);

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        centerRenderer.setBackground(new Color(25, 32, 50));
        centerRenderer.setForeground(new Color(220, 225, 235));
        
        quoteTable.getColumnModel().getColumn(0).setCellRenderer(new TickerIconRenderer());
        quoteTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        quoteTable.getColumnModel().getColumn(2).setCellRenderer(new DarkChangeRenderer());
        quoteTable.getColumnModel().getColumn(3).setCellRenderer(new DarkChangeRenderer());
        quoteTable.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        quoteTable.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);

        quoteTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showTickerContextMenu(e, quoteTable);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showTickerContextMenu(e, quoteTable);
                }
            }
        });

        quoteTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && quoteTable.getSelectedRow() >= 0) {
                int modelRow = quoteTable.convertRowIndexToModel(quoteTable.getSelectedRow());
                String symbol = tableModel.getValueAt(modelRow, 0).toString();
                if (!symbol.contains("No quotes available")) {
                    fetchAndDisplayNews(symbol);
                }
            }
        });

        JScrollPane quoteScroll = new JScrollPane(quoteTable);
        quoteScroll.setBorder(BorderFactory.createLineBorder(new Color(40, 50, 70), 1, true));
        quoteScroll.getViewport().setBackground(new Color(25, 32, 50));

        JPanel quotePanel = new RoundedPanel(26, new Color(25, 32, 50));
        quotePanel.setLayout(new BorderLayout(10, 10));
        quotePanel.setBorder(new EmptyBorder(18, 18, 18, 18));
        JLabel feedTitle = new JLabel("Ticker Feed");
        feedTitle.setForeground(new Color(220, 225, 235));
        feedTitle.setFont(new Font("SansSerif", Font.BOLD, 14));
        quotePanel.add(feedTitle, BorderLayout.NORTH);
        quotePanel.add(quoteScroll, BorderLayout.CENTER);

        JPanel sidePanel = new RoundedPanel(26, new Color(25, 32, 50));
        sidePanel.setLayout(new BorderLayout(10, 10));
        sidePanel.setBorder(new EmptyBorder(18, 18, 18, 18));
        sidePanel.setPreferredSize(new Dimension(220, 0));

        JLabel groupsTitle = new JLabel("Groups");
        groupsTitle.setForeground(new Color(220, 225, 235));
        groupsTitle.setFont(new Font("SansSerif", Font.BOLD, 14));
        sidePanel.add(groupsTitle, BorderLayout.NORTH);

        groupList = new JList<>(groupListModel);
        groupList.setFont(new Font("SansSerif", Font.PLAIN, 14));
        groupList.setBackground(new Color(25, 32, 50));
        groupList.setForeground(new Color(220, 225, 235));
        groupList.setSelectionBackground(new Color(41, 121, 255));
        groupList.setSelectionForeground(Color.WHITE);
        groupList.setFixedCellHeight(34);
        groupList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                refreshQuotesAsync();
            }
        });
        groupList.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showGroupRenamePopup(e);
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    showGroupRenamePopup(e);
                }
            }
        });
        JScrollPane groupScroll = new JScrollPane(groupList);
        groupScroll.setBorder(BorderFactory.createEmptyBorder());
        groupScroll.getViewport().setBackground(new Color(25, 32, 50));
        sidePanel.add(groupScroll, BorderLayout.CENTER);

        // Apply persisted group selection if available, otherwise select 'All'
        if (pendingSelectedGroup != null && !pendingSelectedGroup.isBlank() && groupComboModel.getIndexOf(pendingSelectedGroup) >= 0) {
            groupCombo.setSelectedItem(pendingSelectedGroup);
            groupList.setSelectedValue(pendingSelectedGroup, true);
        } else {
            groupCombo.setSelectedItem("All");
            groupList.setSelectedIndex(0);
        }

        JSplitPane centerSplit = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, quotePanel, sidePanel);
        centerSplit.setResizeWeight(0.78);
        centerSplit.setBorder(null);
        centerSplit.setOpaque(false);

        newsArea.setEditable(false);
        newsArea.setLineWrap(true);
        newsArea.setWrapStyleWord(true);
        newsArea.setFont(new Font("SansSerif", Font.PLAIN, 12));
        newsArea.setForeground(new Color(220, 225, 235));
        newsArea.setBackground(new Color(25, 32, 50));
        newsArea.setText("Select a ticker to view latest news.");

        JScrollPane newsScroll = new JScrollPane(newsArea);
        newsScroll.setBorder(BorderFactory.createLineBorder(new Color(40, 50, 70), 1, true));
        newsScroll.getViewport().setBackground(new Color(25, 32, 50));

        JPanel newsPanel = new RoundedPanel(26, new Color(25, 32, 50));
        newsPanel.setLayout(new BorderLayout(10, 10));
        newsPanel.setBorder(new EmptyBorder(18, 18, 18, 18));
        newsPanel.setPreferredSize(new Dimension(0, 120));
        JLabel newsTitle = new JLabel("Latest News");
        newsTitle.setForeground(new Color(220, 225, 235));
        newsTitle.setFont(new Font("SansSerif", Font.BOLD, 14));
        newsPanel.add(newsTitle, BorderLayout.NORTH);
        newsPanel.add(newsScroll, BorderLayout.CENTER);

        JSplitPane mainSplit = new JSplitPane(JSplitPane.VERTICAL_SPLIT, centerSplit, newsPanel);
        mainSplit.setResizeWeight(0.7);
        mainSplit.setBorder(null);
        mainSplit.setOpaque(false);

        mainPanel.add(mainSplit, BorderLayout.CENTER);

        // Alerts & Activity footer removed per user request; logArea remains for internal logging.

        add(mainPanel, BorderLayout.CENTER);

        addSymbolButton.addActionListener(e -> addTicker(getTickerInput(symbolField).trim().toUpperCase(), getGroupFromCombo(groupCombo)));

        setVisible(true);
    }

    private void setupPlaceholder(JTextComponent textComponent, String placeholder) {
        // Show placeholder initially
        if (textComponent.getText().isEmpty()) {
            textComponent.setText(placeholder);
            textComponent.setFont(new Font("SansSerif", Font.ITALIC, 14));
            textComponent.setForeground(new Color(100, 110, 130));
        }
        
        textComponent.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                // When user clicks the field, if placeholder is showing, select all so typing replaces it
                if (textComponent.getText().equals(placeholder)) {
                    textComponent.selectAll();
                    textComponent.setFont(new Font("SansSerif", Font.PLAIN, 14));
                    textComponent.setForeground(new Color(255, 255, 255));
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                // When user leaves field, restore placeholder if empty
                String text = textComponent.getText().trim();
                if (text.isEmpty()) {
                    textComponent.setText(placeholder);
                    textComponent.setFont(new Font("SansSerif", Font.ITALIC, 14));
                    textComponent.setForeground(new Color(100, 110, 130));
                }
            }
        });
    }

    private void addGroup(String groupName) {
        if (groupName == null || groupName.isBlank() || "All".equalsIgnoreCase(groupName)) {
            showError("Invalid group name.");
            return;
        }
        if (groupComboModel.getIndexOf(groupName) >= 0) {
            showInfo("Group already exists: " + groupName);
            return;
        }
        insertGroupSorted(groupName);
        saveWatchlist();
        log("Group added: " + groupName);
    }

    private void removeGroup(String groupName, JComboBox<String> groupCombo) {
        if (groupName == null || groupName.isBlank() || "All".equalsIgnoreCase(groupName)) {
            showError("Cannot remove the All group or an empty group name.");
            return;
        }
        int index = groupComboModel.getIndexOf(groupName);
        if (index < 0) {
            showError("Group not found: " + groupName);
            return;
        }
        groupComboModel.removeElementAt(index);
        groupListModel.removeElement(groupName);
        synchronized (symbolGroupMap) {
            symbolGroupMap.replaceAll((symbol, group) -> groupName.equals(group) ? "" : group);
        }
        if (groupCombo != null) {
            groupCombo.setSelectedItem("All");
        } else {
            groupList.setSelectedValue("All", true);
        }
        saveWatchlist();
        log("Group removed: " + groupName + "; moved tickers to no-group.");
        refreshQuotesAsync();
    }

    private void showGroupRenamePopup(MouseEvent event) {
        int index = groupList.locationToIndex(event.getPoint());
        if (index < 0) {
            return;
        }
        groupList.setSelectedIndex(index);
        String selectedGroup = groupList.getSelectedValue();
        if (selectedGroup == null || "All".equalsIgnoreCase(selectedGroup)) {
            return;
        }

        JPopupMenu popup = new JPopupMenu();
        JMenuItem renameItem = new JMenuItem("Rename");
        renameItem.addActionListener(e -> renameGroup(selectedGroup));
        popup.add(renameItem);

        JMenuItem refreshItem = new JMenuItem("Refresh");
        refreshItem.addActionListener(e -> refreshQuotesAsync());
        popup.add(refreshItem);

        JMenuItem deleteItem = new JMenuItem("Delete");
        deleteItem.addActionListener(e -> removeGroup(selectedGroup, null));
        popup.add(deleteItem);

        popup.show(groupList, event.getX(), event.getY());
    }

    private void showTickerContextMenu(MouseEvent event, JTable quoteTable) {
        int row = quoteTable.rowAtPoint(event.getPoint());
        if (row < 0) {
            return;
        }
        quoteTable.setRowSelectionInterval(row, row);

        JPopupMenu popup = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("Delete");
        deleteItem.addActionListener(e -> removeSelectedTicker(quoteTable));
        popup.add(deleteItem);

        popup.show(quoteTable, event.getX(), event.getY());
    }

    private void renameGroup(String groupName) {
        if (groupName == null || groupName.isBlank() || "All".equalsIgnoreCase(groupName)) {
            showError("Cannot rename the All group or an empty group name.");
            return;
        }
        String newName = JOptionPane.showInputDialog(this, "Enter new name for group:", groupName);
        if (newName == null) {
            return;
        }
        newName = newName.trim();
        if (newName.isBlank()) {
            showError("Group name cannot be empty.");
            return;
        }
        if (newName.equalsIgnoreCase(groupName)) {
            return;
        }
        for (int i = 0; i < groupComboModel.getSize(); i++) {
            String existing = groupComboModel.getElementAt(i);
            if (existing != null && existing.equalsIgnoreCase(newName)) {
                showError("Group already exists: " + newName);
                return;
            }
        }

        int oldIndex = groupComboModel.getIndexOf(groupName);
        if (oldIndex >= 0) {
            groupComboModel.removeElementAt(oldIndex);
        }
        groupListModel.removeElement(groupName);
        insertGroupSorted(newName);
        final String oldName = groupName;
        final String replacement = newName;
        synchronized (symbolGroupMap) {
            symbolGroupMap.replaceAll((symbol, group) -> oldName.equals(group) ? replacement : group);
        }
        saveWatchlist();
        groupList.setSelectedValue(newName, true);
        log("Group renamed from " + groupName + " to " + newName);
        refreshQuotesAsync();
    }

    private String getGroupFromCombo(JComboBox<String> groupCombo) {
        Object editorItem = groupCombo.getEditor().getItem();
        String val = editorItem == null ? "" : editorItem.toString().trim();
        // Filter out placeholder text and "All"
        if (val.equals("Select Group") || "All".equalsIgnoreCase(val)) {
            return "";
        }
        return val;
    }

    private void addTicker(String symbol, String group) {
        if (symbol.isBlank()) {
            showError("Ticker symbol cannot be empty.");
            return;
        }
        synchronized (symbolGroupMap) {
            if (symbolGroupMap.containsKey(symbol)) {
                showInfo("Ticker already tracked: " + symbol);
                return;
            }
            String actualGroup = group == null || group.isBlank() ? "" : group;
            if (!actualGroup.isBlank() && groupComboModel.getIndexOf(actualGroup) < 0) {
                insertGroupSorted(actualGroup);
            }
            symbolGroupMap.put(symbol, actualGroup);
        }
        saveWatchlist();
        log("Added ticker " + symbol + " to group " + group);
        refreshQuotesAsync();
    }

    private void removeSelectedTicker(JTable quoteTable) {
        int row = quoteTable.getSelectedRow();
        if (row < 0) {
            showError("Select a ticker row to remove.");
            return;
        }
        int modelRow = quoteTable.convertRowIndexToModel(row);
        String symbol = tableModel.getValueAt(modelRow, 0).toString();
        symbolGroupMap.remove(symbol);
        tableModel.removeRow(modelRow);
        saveWatchlist();
        log("Removed ticker: " + symbol);
    }

    private void fetchAndDisplayNews(String symbol) {
        newsArea.setText("Loading news for " + symbol + "...");
        new Thread(() -> {
            try {
                List<StockNewsService.NewsItem> newsList = newsService.fetchNews(symbol);
                SwingUtilities.invokeLater(() -> displayNews(symbol, newsList));
            } catch (Exception e) {
                SwingUtilities.invokeLater(() -> newsArea.setText("Unable to fetch news for " + symbol + ". Error: " + e.getMessage()));
            }
        }).start();
    }

    private void displayNews(String symbol, List<StockNewsService.NewsItem> newsList) {
        if (newsList.isEmpty()) {
            newsArea.setText("No news available for " + symbol + " at this time.");
            return;
        }

        StringBuilder newsText = new StringBuilder();
        newsText.append("Latest News for ").append(symbol).append(":\n\n");
        for (StockNewsService.NewsItem item : newsList) {
            newsText.append("• ").append(item.getTitle()).append("\n");
            if (!item.getSource().isBlank()) {
                newsText.append("  Source: ").append(item.getSource()).append("\n");
            }
            newsText.append("\n");
        }
        newsArea.setText(newsText.toString());
        newsArea.setCaretPosition(0);
    }

    private void refreshQuotesAsync() {
        if (isWallStreetClosed()) {
            SwingUtilities.invokeLater(this::updateMarketClosedStatus);
            return;
        }
        SwingUtilities.invokeLater(() -> marketStatusLabel.setText("Refreshing quotes..."));
        scheduler.execute(this::refreshQuotes);
    }

    private String getTickerInput(JComboBox<String> comboBox) {
        Object item = comboBox.getEditor().getItem();
        String text = item == null ? "" : item.toString();
        // Filter out placeholder text
        return text.equals("Search Ticker..") ? "" : text;
    }

    private void fetchTickerSuggestions(String query, DefaultComboBoxModel<String> model, JComboBox<String> combo) {
        new Thread(() -> {
            try {
                List<String> suggestions = quoteService.fetchTickerSuggestions(query);
                if (suggestions.isEmpty()) {
                    suggestions = getLocalTickerSuggestions(query);
                }
                List<String> finalSuggestions = suggestions;
                SwingUtilities.invokeLater(() -> updateSuggestionModel(finalSuggestions, model, combo));
            } catch (IOException | InterruptedException ignored) {
                List<String> suggestions = getLocalTickerSuggestions(query);
                SwingUtilities.invokeLater(() -> updateSuggestionModel(suggestions, model, combo));
            }
        }).start();
    }

    private void updateSuggestionModel(List<String> suggestions, DefaultComboBoxModel<String> model, JComboBox<String> combo) {
        model.removeAllElements();
        for (String suggestion : suggestions) {
            model.addElement(suggestion);
            if (model.getSize() >= 5) {
                break;
            }
        }
        if (suggestions.isEmpty()) {
            combo.hidePopup();
        } else if (!combo.isPopupVisible()) {
            combo.showPopup();
        }
    }

    private void insertGroupSorted(String groupName) {
        // Insert into combo and list models while keeping 'All' at index 0 and sorting remaining A->Z
        int insertIndex = 1; // after 'All'
        for (int i = 1; i < groupComboModel.getSize(); i++) {
            String existing = groupComboModel.getElementAt(i);
            if (groupName.compareToIgnoreCase(existing) < 0) {
                break;
            }
            insertIndex++;
        }
        groupComboModel.insertElementAt(groupName, insertIndex);
        groupListModel.insertElementAt(groupName, insertIndex);
    }

    private List<String> getLocalTickerSuggestions(String query) {
        if (query == null || query.isBlank()) {
            return List.of();
        }
        String prefix = query.trim().toUpperCase(Locale.US);
        List<String> suggestions = new ArrayList<>();
        for (String symbol : DEFAULT_TICKER_SUGGESTIONS) {
            if (symbol.startsWith(prefix)) {
                suggestions.add(symbol);
            }
            if (suggestions.size() >= 8) {
                return suggestions;
            }
        }
        synchronized (symbolGroupMap) {
            for (String symbol : symbolGroupMap.keySet()) {
                String upper = symbol.toUpperCase(Locale.US);
                if (upper.startsWith(prefix) && !suggestions.contains(upper)) {
                    suggestions.add(upper);
                }
                if (suggestions.size() >= 8) {
                    break;
                }
            }
        }
        return suggestions;
    }

    private void startRefreshTimer() {
        scheduler.scheduleAtFixedRate(this::refreshQuotes, 0, 60, TimeUnit.SECONDS);
    }

    private void loadWatchlist() {
        WatchlistStore.WatchlistData data = watchlistStore.load();
        Set<String> groups = new LinkedHashSet<>(data.groups());
        // Prepare sorted group list (exclude empty and 'All')
        List<String> sorted = groups.stream()
                .filter(g -> g != null && !g.isBlank() && !"All".equalsIgnoreCase(g))
                .sorted(String.CASE_INSENSITIVE_ORDER)
                .toList();
        // Add 'All' first
        groupComboModel.addElement("All");
        groupListModel.addElement("All");
        for (String group : sorted) {
            groupComboModel.addElement(group);
            groupListModel.addElement(group);
        }
        // remember loaded selection to apply after UI initialization
        pendingSelectedGroup = data.selectedGroup();
        data.symbolGroups().forEach(symbolGroupMap::put);
    }

    private void saveWatchlist() {
        Set<String> groups = new LinkedHashSet<>();
        for (int i = 0; i < groupComboModel.getSize(); i++) {
            String g = groupComboModel.getElementAt(i);
            if (g == null || g.isBlank() || "All".equalsIgnoreCase(g)) continue;
            groups.add(g);
        }
        String selected = groupList == null ? "" : (groupList.getSelectedValue() == null ? "" : groupList.getSelectedValue());
        watchlistStore.save(symbolGroupMap, groups, selected);
    }

    private void refreshQuotes() {
        if (isWallStreetClosed()) {
            SwingUtilities.invokeLater(this::updateMarketClosedStatus);
            return;
        }

        Map<String, String> symbolGroupSnapshot;
        synchronized (symbolGroupMap) {
            symbolGroupSnapshot = new LinkedHashMap<>(symbolGroupMap);
        }
        List<String> symbols = symbolGroupSnapshot.keySet().stream().toList();
        if (symbols.isEmpty()) {
            SwingUtilities.invokeLater(() -> marketStatusLabel.setText("Add tickers to start live tracking."));
            return;
        }
        try {
            Map<String, StockItem> updated = quoteService.fetchQuotes(symbols, symbolGroupSnapshot);
            SwingUtilities.invokeLater(() -> updateTable(updated));
        } catch (IOException | InterruptedException ex) {
            String message = ex.getMessage();
            if (message != null && message.contains("HTTP 429")) {
                SwingUtilities.invokeLater(() -> {
                    marketStatusLabel.setText("Rate limited by quote provider; retrying soon.");
                    log("Unable to refresh quotes: " + message);
                });
            } else {
                SwingUtilities.invokeLater(() -> showError("Unable to refresh quotes: " + message));
            }
        }
    }

    private void updateTable(Map<String, StockItem> updatedQuotes) {
        tableModel.setRowCount(0);
        int positive = 0;
        int negative = 0;
        int rowsAdded = 0;
        String selectedGroup = groupList == null ? null : groupList.getSelectedValue();
        boolean showAll = selectedGroup == null || selectedGroup.isBlank() || "All".equalsIgnoreCase(selectedGroup);
        for (StockItem item : updatedQuotes.values()) {
            if (!showAll && !selectedGroup.equals(item.group())) {
                continue;
            }
            String priceText = Double.isFinite(item.price()) ? String.format("%.2f", item.price()) : "N/A";
            String changeText = Double.isFinite(item.change()) ? String.format("%.2f", item.change()) : "N/A";
            String changePercentText = Double.isFinite(item.changePercent()) ? String.format("%.2f%%", item.changePercent()) : "N/A";
            tableModel.addRow(new Object[]{
                item.symbol(),
                priceText,
                changeText,
                changePercentText,
                item.shortName(),
                item.updatedAt()
            });
            rowsAdded++;
            if (Double.isFinite(item.change()) && item.change() > 0) {
                positive++;
            } else if (Double.isFinite(item.change()) && item.change() < 0) {
                negative++;
            }
        }
        if (rowsAdded == 0) {
            tableModel.addRow(new Object[]{"No quotes available yet. Add tickers to see live data.", "", "", "", "", ""});
        }

        boolean marketClosed = isWallStreetClosed();
        String direction = marketClosed ? "Market Closed" : (positive >= negative ? "Market Up" : "Market Down");
        String refreshTime = marketClosed && !lastRefreshTime.isBlank() ? lastRefreshTime : now();
        if (!marketClosed) {
            lastRefreshTime = refreshTime;
            lastRefreshedRows = rowsAdded;
        }

        marketStatusLabel.setText(direction + " — " + rowsAdded + " tickers refreshed at " + refreshTime + ".");
        if (!direction.equals(currentDirection)) {
            String message = "Market direction changed to " + direction + " at " + refreshTime;
            log(message);
            displayNotification("Stock Tracker", message, TrayIcon.MessageType.INFO);
            currentDirection = direction;
        }
    }

    private void updateMarketClosedStatus() {
        if (lastRefreshTime.isBlank()) {
            marketStatusLabel.setText("Market Closed — no recent quote refresh available.");
        } else {
            marketStatusLabel.setText("Market Closed — " + lastRefreshedRows + " tickers refreshed at " + lastRefreshTime + ".");
        }
        if (!"Market Closed".equals(currentDirection)) {
            String message = "Market direction changed to Market Closed at " + (lastRefreshTime.isBlank() ? now() : lastRefreshTime);
            log(message);
            displayNotification("Stock Tracker", message, TrayIcon.MessageType.INFO);
            currentDirection = "Market Closed";
        }
    }

    private boolean isWallStreetClosed() {
        LocalDateTime nowEastern = LocalDateTime.now(ZoneId.of("America/New_York"));
        DayOfWeek day = nowEastern.getDayOfWeek();
        if (day == DayOfWeek.SATURDAY || day == DayOfWeek.SUNDAY) {
            return true;
        }
        LocalTime time = nowEastern.toLocalTime();
        LocalTime marketOpen = LocalTime.of(9, 30);
        LocalTime marketClose = LocalTime.of(16, 0);
        return time.isBefore(marketOpen) || !time.isBefore(marketClose);
    }

    private void log(String message) {
        logArea.append("[" + now() + "] " + message + "\n");
        logArea.setCaretPosition(logArea.getDocument().getLength());
    }

    private String now() {
        return LocalDateTime.now().format(DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm:ss"));
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Stock Tracker", JOptionPane.ERROR_MESSAGE);
        log("ERROR: " + message);
    }

    private void showInfo(String message) {
        JOptionPane.showMessageDialog(this, message, "Stock Tracker", JOptionPane.INFORMATION_MESSAGE);
    }

    private void initSystemTray() {
        if (!SystemTray.isSupported()) {
            log("System tray not supported on this platform.");
            systemTraySupported = false;
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            return;
        }

        SystemTray tray = SystemTray.getSystemTray();
        Image icon = createTrayIconImage();
        PopupMenu popup = new PopupMenu();

        MenuItem openItem = new MenuItem("Show Window");
        openItem.addActionListener(e -> showWindow());
        popup.add(openItem);

        MenuItem refreshItem = new MenuItem("Refresh Now");
        refreshItem.addActionListener(e -> refreshQuotesAsync());
        popup.add(refreshItem);

        popup.addSeparator();

        MenuItem exitItem = new MenuItem("Exit");
        exitItem.addActionListener(e -> {
            scheduler.shutdownNow();
            tray.remove(trayIcon);
            System.exit(0);
        });
        popup.add(exitItem);

        trayIcon = new TrayIcon(icon, "Stock Tracker", popup);
        trayIcon.setImageAutoSize(true);
        trayIcon.addActionListener(e -> showWindow());

        try {
            tray.add(trayIcon);
            systemTraySupported = true;
            log("System tray initialized. App will continue running when the window is closed.");
        } catch (AWTException ex) {
            systemTraySupported = false;
            setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            log("Unable to add system tray icon: " + ex.getMessage());
        }
    }

    private Image createTrayIconImage() {
        int size = 16;
        BufferedImage image = new BufferedImage(size, size, BufferedImage.TYPE_INT_ARGB);
        var graphics = image.createGraphics();
        graphics.setColor(new java.awt.Color(0, 120, 215));
        graphics.fillOval(0, 0, size, size);
        graphics.setColor(java.awt.Color.WHITE);
        graphics.drawString("S", 4, 12);
        graphics.dispose();
        return image;
    }

    private void showWindow() {
        SwingUtilities.invokeLater(() -> {
            if (!isVisible()) {
                setVisible(true);
            }
            setExtendedState(JFrame.NORMAL);
            toFront();
            repaint();
        });
    }

    private void displayNotification(String title, String message, TrayIcon.MessageType messageType) {
        if (systemTraySupported && trayIcon != null) {
            trayIcon.displayMessage(title, message, messageType);
        }
        log(title + ": " + message);
    }

    private static JButton createPrimaryButton(String text) {
        RoundedButton button = new RoundedButton(text);
        button.setFont(new Font("SansSerif", Font.BOLD, 14));
        button.setBackground(new Color(65, 150, 255));
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createEmptyBorder(10, 16, 10, 16));
        button.setContentAreaFilled(true);
        button.setOpaque(false);
        return button;
    }

    private static JButton createSecondaryButton(String text) {
        JButton button = new JButton(text);
        button.setFont(new Font("SansSerif", Font.BOLD, 14));
        button.setBackground(new Color(242, 244, 248));
        button.setForeground(new Color(30, 33, 38));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createEmptyBorder(10, 16, 10, 16));
        return button;
    }

    private static class RoundedButton extends JButton {
        private static final int ARC_RADIUS = 12;
        
        public RoundedButton(String text) {
            super(text);
        }
        
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(getBackground());
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), ARC_RADIUS, ARC_RADIUS);
            g2.dispose();
            super.paintComponent(g);
        }
        
        @Override
        protected void paintBorder(java.awt.Graphics g) {
            // No border needed
        }
    }

    private static class TickerIconRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                                                       boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if (isSelected) {
                c.setBackground(table.getSelectionBackground());
                c.setForeground(table.getSelectionForeground());
            } else {
                c.setBackground(new Color(25, 32, 50));
                c.setForeground(new Color(220, 225, 235));
            }
            
            if (value != null) {
                String symbol = value.toString().toUpperCase();
                ImageIcon logo = CompanyLogoCache.getLogoForTicker(symbol);
                
                if (logo != null) {
                    // Display with company logo
                    setIcon(logo);
                    setText("  " + symbol);
                } else {
                    // Fallback to emoji if logo not available
                    setIcon(null);
                    String icon = getIconForTicker(symbol);
                    setText(icon + " " + symbol);
                }
            }
            setHorizontalAlignment(JLabel.LEFT);
            setFont(new Font("SansSerif", Font.PLAIN, 14));
            setVerticalAlignment(JLabel.CENTER);
            return this;
        }
        
        private String getIconForTicker(String symbol) {
            return switch (symbol) {
                case "AAPL", "MSFT", "GOOGL", "GOOG", "META" -> "💻";
                case "TSLA", "RIVN", "LCID", "NIO" -> "🚗";
                case "NVDA", "AMD", "AVGO" -> "🔧";
                case "JPM", "BAC", "GS" -> "🏦";
                case "PFE", "JNJ", "AZN" -> "💊";
                case "XOM", "CVX", "COP" -> "⚡";
                case "AMZN", "WMT", "HD" -> "🛒";
                case "NFLX", "DIS", "PARA" -> "📺";
                default -> "📈";
            };
        }
    }

    private static class DarkChangeRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                                                       boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            setHorizontalAlignment(JLabel.CENTER);
            
            if (isSelected) {
                c.setForeground(table.getSelectionForeground());
                c.setBackground(table.getSelectionBackground());
            } else {
                c.setBackground(new Color(16, 22, 35));
                if (value != null) {
                    String text = value.toString().replace("%", "").trim();
                    try {
                        double amount = Double.parseDouble(text.replace("%", ""));
                        if (amount > 0) {
                            c.setForeground(new Color(76, 175, 80));
                        } else if (amount < 0) {
                            c.setForeground(new Color(255, 87, 51));
                        } else {
                            c.setForeground(new Color(150, 160, 175));
                        }
                    } catch (NumberFormatException e) {
                        c.setForeground(new Color(150, 160, 175));
                    }
                } else {
                    c.setForeground(new Color(150, 160, 175));
                }
            }
            return c;
        }
    }

    private static class RoundedPanel extends JPanel {
        private final int radius;
        private final Color backgroundColor;

        public RoundedPanel(int radius, Color bgColor) {
            super();
            this.radius = radius;
            this.backgroundColor = bgColor;
            setOpaque(false);
        }

        @Override
        protected void paintComponent(java.awt.Graphics g) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(backgroundColor);
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
            g2.dispose();
            super.paintComponent(g);
        }
    }

    private static class ChangeCellRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                                                       boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if (isSelected) {
                c.setForeground(table.getSelectionForeground());
                c.setBackground(table.getSelectionBackground());
            } else {
                c.setBackground(new Color(245, 248, 252));
                if (value != null) {
                    String text = value.toString().replace("%", "").trim();
                    try {
                        double amount = Double.parseDouble(text.replace("%", ""));
                        if (amount > 0) {
                            c.setForeground(new Color(0, 146, 69));
                        } else if (amount < 0) {
                            c.setForeground(new Color(255, 59, 48));
                        } else {
                            c.setForeground(new Color(108, 115, 127));
                        }
                    } catch (NumberFormatException e) {
                        c.setForeground(new Color(108, 115, 127));
                    }
                }
            }
            setHorizontalAlignment(JLabel.RIGHT);
            return c;
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(App::new);
    }
}
