/*
 * This source file was generated by the Gradle 'init' task
 */
package stock.tracker;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appConstructsSuccessfully() {
        assertDoesNotThrow(App::new, "Stock Tracker desktop app should construct without error");
    }
}
